import Head from 'next/head'
import { FaBattleNet } from 'react-icons/fa'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rolando Valle Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 '>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <FaBattleNet className='text-2xl' />
            <ul className='flex items-center gap-3 uppercase font-bold text-xs '>
              <li>
                <a href='#about'>About</a>
              </li>
              <li>
                <a href='#projects'>Projects</a>
              </li>
              <li>
                <a href='#contact'>Contact</a>
              </li>
            </ul>
          </nav>
          <div className='h-full flex flex-col justify-center align-center uppercase'>
            <h2 className='PlayfairDisplay text-5xl py-2 font-medium text-center'>
              Rolando Valle
            </h2>
            <h3 className='text-center text-xs tracking-widest font-bold'>
              Web Developer | UI UX Design
            </h3>
          </div>
        </section>
      </main>
    </div>
  )
}
