import Head from 'next/head'
import { BsMoonStarsFill } from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Rolando Valle Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>Lance/Coder</h1>
            <ul className='flex items-center'>
              <li>
                <BsMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className='cursor-pointer text-2xl'
                />
              </li>
              <li>
                <a
                  href='#'
                  className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
              Rolando Valle
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl'>
              Web Developer / UI UX Design
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>
              I am a self-taught web developer with a passion for learning new
              skills and programming. My current experience has been primarily
              in front-end development, I have taken several courses online
              about web development, including Freecodecamp, the Odin Project,
              Coursera, Skillshare, YouTube and Udemy. I am looking for a career
              shift into technology to develop my skills in front-end
              development My background also includes a strong knowledge of
              digital marketing, copy writing and graphics design
            </p>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className='relative flex justify-center align-items-center mx-auto bg-gradient-to-b from-teal-500 to-white rounded-full max-w-[320px] h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={deved} alt='avatar' layout='fill' objectFit='cover' />
            </div>
          </div>
        </section>
        {/* section 2 */}
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi
              esse vel voluptate fugiat, quae aperiam.{' '}
              <span className='text-teal-500'>agencies</span> Lorem, ipsum dolor
              sit amet consectetur adipisicing elit. Repudiandae, distinctio!{' '}
              <span className='text-teal-500'>start ups</span> Lorem ipsum
              dolor, sit amet consectetur adipisicing elit. Voluptates voluptas
              iste, non eos accusamus dolore.
            </p>
            <p lassName='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit.
              Explicabo tenetur debitis perspiciatis neque enim velit ipsum
              aliquam, quidem totam iste.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-md p-10 rounded-xl my-10'>
              <Image src={design} alt='desing' width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Beautiful Designs
              </h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi
                debitis dolorem rem perferendis deserunt labore, voluptatem
                consequatur ea sit aut!
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-md p-10 rounded-xl my-10'>
              <Image src={consulting} alt='desing' width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Beautiful Designs
              </h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi
                debitis dolorem rem perferendis deserunt labore, voluptatem
                consequatur ea sit aut!
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-md p-10 rounded-xl my-10'>
              <Image src={code} alt='desing' width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Beautiful Designs
              </h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi
                debitis dolorem rem perferendis deserunt labore, voluptatem
                consequatur ea sit aut!
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi
              esse vel voluptate fugiat, quae aperiam.{' '}
              <span className='text-teal-500'>agencies</span> Lorem, ipsum dolor
              sit amet consectetur adipisicing elit. Repudiandae, distinctio!{' '}
              <span className='text-teal-500'>start ups</span> Lorem ipsum
              dolor, sit amet consectetur adipisicing elit. Voluptates voluptas
              iste, non eos accusamus dolore.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web1}
                alt='web1'
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web2}
                alt='web2'
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web3}
                alt='web3'
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web4}
                alt='web4'
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web5}
                alt='web5'
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={web6}
                alt='web6'
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
