import Head from 'next/head'
import { BsMoonStarsFill } from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rolando Valle Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>Lance/Coder</h1>
            <ul className='flex items-center'>
              <li>
                <BsMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a
                  href='#'
                  className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>
              Rolando Valle
            </h2>
            <h3 className='text-2xl py-2'>Web Developer / UI UX Design</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              I am a self-taught web developer with a passion for learning new
              skills and programming. My current experience has been primarily
              in front-end development, I have taken several courses online
              about web development, including Freecodecamp, the Odin Project,
              Coursera, Skillshare, YouTube and Udemy. I am looking for a career
              shift into technology to develop my skills in front-end
              development My background also includes a strong knowledge of
              digital marketing, copy writing and graphics design
            </p>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 to-white rounded-full w-80 h-80 mt-20 overflow-hidden'>
              <Image src={deved} alt='avatar' layout='fill' objectFit='cover' />
            </div>
          </div>
        </section>
        {/* section 2 */}
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi
              esse vel voluptate fugiat, quae aperiam.
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}
